import os

OUTPUT_DIR = os.getenv("OUTPUT_DIR")
REFERENCE_DATA_PATH = os.getenv("REFERENCE_DATA_PATH")
SCORING_FILE_SOURCE_DIR = os.getenv("SCORING_FILE_SOURCE_DIR")
SCORING_FILE_TARGET_DIR = os.getenv("SCORING_FILE_TARGET_DIR")
NF_WORK_DIR = os.getenv("NF_WORK_DIR", "/app/work")