services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zod50902
      POSTGRES_DB: snpster_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always

  job_runner:
    build: 
      context: ..
      dockerfile: docker/job_runner/Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: snpster_db
      DB_USER: postgres
      DB_PASSWORD: zod50902

      NEXTFLOW_BIN: /usr/local/bin/nextflow
      NEXTFLOW_CONFIG: /app/nextflow/nextflow.config
      PIPELINE_PATH: /app/nextflow/pipeline_orchestrator.nf
      SAMPLESHEET_PATH: /app/job_runner_module/samplesheet.csv
      NXF_HOME: /srv/imputed/nf_runtime/.nextflow
      NXF_WORK: /srv/imputed/nf_runtime/nf_work

      BASE_OUTPUT_DIR: /srv/imputed
      IMPUTATION_DEPENDENCIES: /home/frederik/shared_drive/snpster_dependencies/imputer_dependencies
      HARMONIZER_DEPENDENCIES: /home/frederik/shared_drive/snpster_dependencies/harmonizer_dependencies
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/frederik/shared_drive:/home/frederik/shared_drive
      - /srv/imputed:/srv/imputed
      - ..:/app
    depends_on:
      - postgres
    restart: always