services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zod50902
      POSTGRES_DB: snpster_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always

  imputation_runner:
    build: 
      context: ..
      dockerfile: docker/imputation_runner/Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: snpster_db
      DB_USER: postgres
      DB_PASSWORD: zod50902

      NEXTFLOW_BIN: /usr/local/bin/nextflow
      NEXTFLOW_CONFIG: /app/nextflow/nextflow.config
      PIPELINE_PATH: /app/nextflow/pipeline_orchestrator.nf
      SAMPLESHEET_PATH: /app/imputation_runner_module/samplesheet.csv
      NXF_HOME: /srv/imputed/nf_runtime/.nextflow
      NXF_WORK: /srv/imputed/nf_runtime/nf_work
      BASE_OUTPUT_DIR: /srv/imputed
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #mount socket such that docker container only needs client to run nextflow pipeline which calls other docker containers to avoid dockerin docker issues
      - /srv/imputed:/srv/imputed # this is where the imputation outputs will be stored, must mount to :/srv/imputed, s3 bucket in the future
      - ..:/app #why is this mounted?
      - /srv/dependencies/imputer:/app/dependencies/imputer:ro #imputation dependencies, must mount to :/app/dependencies/imputer
      - /srv/dependencies/harmonizer:/app/dependencies/harmonizer:ro  #harmonizer dependencies, must mount to :/app/dependencies/harmonizer
    depends_on:
      - postgres
    restart: always