-- Initialize database with custom schema
-- This file will be executed when the PostgreSQL container starts

CREATE SCHEMA IF NOT EXISTS snpster_users;
CREATE SCHEMA IF NOT EXISTS data_libraries;

CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER DATABASE snpster_db SET search_path = snpster_users, public;

CREATE SEQUENCE IF NOT EXISTS snpster_users.imputation_jobs_seq START 1;
CREATE SEQUENCE IF NOT EXISTS snpster_users.prsc_jobs_seq START 1;
CREATE SEQUENCE IF NOT EXISTS snpster_users.report_jobs_seq START 1;

-- ===================================
-- User information table(s) to store user details
-- ===================================

CREATE TABLE snpster_users.user_information (
    user_id varchar(100) PRIMARY KEY NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE snpster_users.user_files (
    file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id VARCHAR(100) NOT NULL
        REFERENCES snpster_users.user_information(user_id)
        ON DELETE CASCADE,

    genefile_location TEXT NOT NULL,

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE snpster_users.user_ancestry (
    user_id VARCHAR(100) PRIMARY KEY
        REFERENCES snpster_users.user_information(user_id)
        ON DELETE CASCADE,

    eur NUMERIC(8,6) CHECK (eur >= 0 AND eur <= 1),
    afr NUMERIC(8,6) CHECK (afr >= 0 AND afr <= 1),
    eas NUMERIC(8,6) CHECK (eas >= 0 AND eas <= 1),
    sas NUMERIC(8,6) CHECK (sas >= 0 AND sas <= 1),
    amr NUMERIC(8,6) CHECK (amr >= 0 AND amr <= 1),

    primary_ancestry VARCHAR(10)
        CHECK (primary_ancestry IN ('EUR', 'AFR', 'EAS', 'SAS', 'AMR')),

    primary_ancestry_percentage NUMERIC(8,6)
        CHECK (primary_ancestry_percentage >= 0 AND primary_ancestry_percentage <= 1),

    ancestry_method VARCHAR(100),
    reference_panel VARCHAR(100),

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ===================================
-- Tables for storing information about the PGS scores
-- ===================================

CREATE TABLE data_libraries.pgscatalog_data (
    pgs_id varchar(100) PRIMARY KEY,
    pgs_name VARCHAR(255),
    reported_trait VARCHAR(255),
    mapped_trait_efo_label VARCHAR(255),
    efo_id VARCHAR(255),
    pgs_development_method VARCHAR(255),
    pgs_development_details TEXT,
    original_genome_build VARCHAR(20),
    number_of_variants INTEGER,
    number_of_interaction_terms INTEGER,
    type_of_variant_weight TEXT,
    pgp_id varchar(100),
    publication_pmid int,
    publication_doi VARCHAR(255),
    score_and_results_match_original_publication BOOLEAN,
    ancestry_distribution_source_of_variant_associations_gwas VARCHAR(255),
    ancestry_distribution_score_development_training VARCHAR(255),
    ancestry_distribution_pgs_evaluation VARCHAR(255),
    ftp_link VARCHAR(255),
    release_date DATE,
    license_terms_of_use TEXT
);


CREATE TABLE data_libraries.pgs_publications (
    pgp_id varchar(100) PRIMARY KEY,
    first_author VARCHAR(255),
    title VARCHAR(255),
    journal_name VARCHAR(255),
    publication_date DATE,
    release_date DATE,
    authors TEXT,
    digital_object_identifier_doi VARCHAR(255),
    pubmed_id_pmid VARCHAR(20)
);

CREATE TABLE data_libraries.ontology_mappings (
    ontology_id varchar(100) PRIMARY KEY,
    ontology_label VARCHAR(255),
    ontology_description TEXT,
    ontology_url VARCHAR(255)
);

CREATE TABLE data_libraries.pgs_performance (
    ppm_id varchar(100) PRIMARY KEY,
    pgs_id varchar(100) REFERENCES data_libraries.pgscatalog_data(pgs_id) ON DELETE CASCADE,
    pss_id varchar(100),
    pgp_id varchar(100) REFERENCES data_libraries.pgs_publications(pgp_id) ON DELETE CASCADE,
    reported_trait VARCHAR(255),
    covariates_included_in_model TEXT,
    pgs_performance_other_relevant_info TEXT,
    publication_pmid int,
    publication_doi VARCHAR(255),
    hazard_ratio DECIMAL(10,6),
    hazard_ratio_ci_lower DECIMAL(10,6),
    hazard_ratio_ci_upper DECIMAL(10,6),
    odds_ratio DECIMAL(10,6),
    odds_ratio_ci_lower DECIMAL(10,6),
    odds_ratio_ci_upper DECIMAL(10,6),
    beta DECIMAL(10,6),
    auroc DECIMAL(5,2),
    concordance_statistic DECIMAL(5,2),
    other_metric TEXT
);

CREATE TABLE data_libraries.score_development_samples ( 
    pgs_id VARCHAR(50), 
    stage_of_pgs_development VARCHAR(100), 
    individuals_development INTEGER, 
    cases_development INTEGER, 
    controls_development INTEGER, 
    percent_male_development FLOAT,
    broad_ancestry_category text
); 

CREATE TABLE data_libraries.evaluation_sample_sets (
    pss_id VARCHAR(50),
    pgs_id VARCHAR(50) REFERENCES data_libraries.pgscatalog_data(pgs_id) ON DELETE CASCADE, 
    individuals_evaluation INTEGER, 
    cases_evaluation INTEGER, 
    controls_evaluation INTEGER, 
    percent_male_evaluation FLOAT,
    broad_ancestry_category text,
    country_of_recruitment text,
    cohort text
);

CREATE TABLE data_libraries.pipeline_dependencies (
    module varchar(100),
    dependency_name VARCHAR(100),
    file_path TEXT,
    PRIMARY KEY (module, dependency_name, file_path)
);

-- ===================================
-- Tables for handling everything from user uploaded data to imputation
-- ===================================

CREATE TABLE snpster_users.imputation_jobs (
    imputation_id integer PRIMARY KEY DEFAULT nextval('snpster_users.imputation_jobs_seq') NOT NULL,

    user_id varchar(100) NOT NULL
        REFERENCES snpster_users.user_information(user_id)
        ON DELETE CASCADE,

    imputation_status VARCHAR(20)
        CHECK (imputation_status IN ('queued', 'running', 'completed', 'failed')),

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

CREATE TABLE snpster_users.imputation_job_parameters (
    imputation_id integer NOT NULL
        REFERENCES snpster_users.imputation_jobs(imputation_id)
        ON DELETE CASCADE,

    file_id BIGINT NOT NULL
        REFERENCES snpster_users.user_files(file_id)
        ON DELETE CASCADE,

    PRIMARY KEY (imputation_id, file_id)
);

CREATE TABLE snpster_users.imputed_data (
    imputation_id integer NOT NULL REFERENCES snpster_users.imputation_jobs(imputation_id) ON DELETE CASCADE,
    file_path TEXT,
    number_of_variants INTEGER,
    chromosome smallint CHECK (chromosome >= 1 AND chromosome <= 22),
    PRIMARY KEY (imputation_id, chromosome)
);

-- ===================================
-- Reporting tables for post-imputation jobs
-- ===================================



CREATE TABLE snpster_users.prsc_jobs (
    imputation_id integer NOT NULL REFERENCES snpster_users.imputation_jobs(imputation_id) ON DELETE CASCADE,
    prsc_id integer PRIMARY KEY DEFAULT nextval('snpster_users.prsc_jobs_seq') NOT NULL,
    prsc_status VARCHAR(20) CHECK (prsc_status IN ('queued', 'running', 'completed', 'failed')),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

CREATE TABLE snpster_users.prsc_job_parameters (
    prsc_id integer NOT NULL REFERENCES snpster_users.prsc_jobs(prsc_id) ON DELETE CASCADE,
    pgs_id varchar(100) NOT NULL REFERENCES data_libraries.pgscatalog_data(pgs_id) ON DELETE CASCADE,
    PRIMARY KEY (prsc_id, pgs_id)
);

CREATE TABLE snpster_users.prsc_job_results (
    prsc_id integer NOT NULL REFERENCES snpster_users.prsc_jobs(prsc_id) ON DELETE CASCADE,
    pgs_id varchar(100) NOT NULL REFERENCES data_libraries.pgscatalog_data(pgs_id) ON DELETE CASCADE,
    score_sum NUMERIC,
    percentile_most_similar_pop DECIMAL(8,5) CHECK (percentile_most_similar_pop >= 0 AND percentile_most_similar_pop <= 100),
    z_norm1 DECIMAL(8,5),
    z_norm2 DECIMAL(8,5),
    z_most_similar_pop DECIMAL(8,5),
    percent_variants_matched DECIMAL(8,5),
    n_variants_matched INTEGER,
    PRIMARY KEY (prsc_id, pgs_id)
);

CREATE TABLE snpster_users.pgs_reports_shop(
    pgs_id varchar(100) NOT NULL REFERENCES data_libraries.pgscatalog_data(pgs_id),
    report_name VARCHAR(255) NOT NULL,
    scoring_file_path TEXT,
    PRIMARY KEY (pgs_id, report_name),
    CONSTRAINT pgs_reports_shop_one_scoring_path_per_pgs
        EXCLUDE USING gist (pgs_id WITH =, scoring_file_path WITH <>)
);

CREATE TABLE snpster_users.report_jobs (
    prsc_id integer NOT NULL REFERENCES snpster_users.prsc_jobs(prsc_id) ON DELETE CASCADE,
    report_id integer PRIMARY KEY DEFAULT nextval('snpster_users.report_jobs_seq') NOT NULL,
    report_status VARCHAR(20) CHECK (report_status IN ('queued', 'running', 'completed', 'failed')),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

-- ===================================
-- Trigger: create imputation job when a new user is created
-- ===================================

CREATE OR REPLACE FUNCTION snpster_users.create_imputation_job_for_new_file()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    new_imputation_id integer;
BEGIN
    INSERT INTO snpster_users.imputation_jobs (
        user_id,
        imputation_status
    )
    VALUES (
        NEW.user_id,
        'queued'
    )
    RETURNING imputation_id INTO new_imputation_id;

    INSERT INTO snpster_users.imputation_job_parameters (
        imputation_id,
        file_id
    )
    VALUES (
        new_imputation_id,
        NEW.file_id
    );

    INSERT INTO snpster_users.user_ancestry (
        user_id
    )
    VALUES (
        NEW.user_id
    )
    ON CONFLICT (user_id) DO NOTHING;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_create_imputation_job_on_user_insert
ON snpster_users.user_information;

DROP TRIGGER IF EXISTS trg_create_imputation_job_on_file_insert
ON snpster_users.user_files;

CREATE TRIGGER trg_create_imputation_job_on_file_insert
AFTER INSERT ON snpster_users.user_files
FOR EACH ROW
EXECUTE FUNCTION snpster_users.create_imputation_job_for_new_file();
-- ===================================
-- Trigger: set started_at / completed_at timestamps on status changes
-- ===================================

CREATE OR REPLACE FUNCTION snpster_users.set_imputation_job_timestamps()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.imputation_status = 'running' AND (OLD.imputation_status IS DISTINCT FROM 'running') THEN
        NEW.started_at := CURRENT_TIMESTAMP;
    END IF;
    IF NEW.imputation_status = 'completed' AND (OLD.imputation_status IS DISTINCT FROM 'completed') THEN
        NEW.completed_at := CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION snpster_users.set_prsc_job_timestamps()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.prsc_status = 'running' AND (OLD.prsc_status IS DISTINCT FROM 'running') THEN
        NEW.started_at := CURRENT_TIMESTAMP;
    END IF;
    IF NEW.prsc_status = 'completed' AND (OLD.prsc_status IS DISTINCT FROM 'completed') THEN
        NEW.completed_at := CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION snpster_users.set_report_job_timestamps()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.report_status = 'running' AND (OLD.report_status IS DISTINCT FROM 'running') THEN
        NEW.started_at := CURRENT_TIMESTAMP;
    END IF;
    IF NEW.report_status = 'completed' AND (OLD.report_status IS DISTINCT FROM 'completed') THEN
        NEW.completed_at := CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_imputation_job_timestamps ON snpster_users.imputation_jobs;
CREATE TRIGGER trg_imputation_job_timestamps
BEFORE UPDATE OF imputation_status ON snpster_users.imputation_jobs
FOR EACH ROW
EXECUTE FUNCTION snpster_users.set_imputation_job_timestamps();

DROP TRIGGER IF EXISTS trg_prsc_job_timestamps ON snpster_users.prsc_jobs;
CREATE TRIGGER trg_prsc_job_timestamps
BEFORE UPDATE OF prsc_status ON snpster_users.prsc_jobs
FOR EACH ROW
EXECUTE FUNCTION snpster_users.set_prsc_job_timestamps();

DROP TRIGGER IF EXISTS trg_report_job_timestamps ON snpster_users.report_jobs;
CREATE TRIGGER trg_report_job_timestamps
BEFORE UPDATE OF report_status ON snpster_users.report_jobs
FOR EACH ROW
EXECUTE FUNCTION snpster_users.set_report_job_timestamps();