FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends default-jre-headless && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 1) Python deps first (only changes when requirements.txt changes)
COPY imputation_module/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# 2) Big dependencies next (only changes when these files change)
RUN mkdir -p /data /work /output /test_files

COPY imputation_module/big_dependencies/beagle_references /data/beagle_references
COPY imputation_module/big_dependencies/plink.GRCh38.map /data/plink.GRCh38.map

ENV PLINK_MAP_DIR=/data/plink.GRCh38.map
ENV BEAGLE_REFERENCE_DIR=/data/beagle_references

# 3) App code last (this is what you change often)
COPY imputation_module/ /app/

ENV BEAGLE_JAR=/app/dependencies/beagle.27Feb25.75f.jar
ENV JAVA_EXE=/usr/bin/java
ENV HEAP_GB=6
ENV THREADS=2
ENV GP_MIN=0.90
ENV DS_TOL=0.05
ENV SNPS_ONLY=True
ENV BIALLELIC_ONLY=True
ENV POLARS_MAX_THREADS=1
ENV DF_ENGINE=polars
ENV VCF_FILES_DIR=/app/dependencies/test_data
ENV OUTPUT_DIR=/output

CMD ["python", "main.py"]
