# Use Python base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

RUN mkdir -p /data

COPY harmonizing_module/big_dependencies/all_phase3.pvar.zst /data/all_phase3.pvar.zst
COPY harmonizing_module/big_dependencies/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz /data/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

ENV PLINK_REFERENCE_FASTA=/data/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
ENV PVAR_REF_FILE=/data/all_phase3.pvar.zst
ENV PLINK_PREFIX=plink_temp



# Copy and install Python requirements
COPY harmonizing_module/requirements.txt .
RUN pip install -r requirements.txt

# Copy all project files from harmonizing_module
COPY harmonizing_module/ .

# ---- Paths *inside the container* ----
# These three are baked into the image
ENV PLINK_1_9_PATH=/app/dependencies/plink
ENV PLINK_2_0_PATH=/app/dependencies/plink2
ENV TEST_FILE=/app/dependencies/genome_Frederik_FangelTolberg_v5_Full_20241117223640.txt
ENV PLINK_1_9_MEMORY_MB=4000



# Run your script
CMD ["python", "main.py"]
